logging:
  level:
    root: info # springboot框架本身的级别
    com.zzspace.blog: debug
  file:
    name: log/bolg.log
server:
  port: 8081
zzspace.blog:
  topk: 6
  avatar:
      tourist: /images/tourist.png
      admin: /images/admin.jpg
  imagePath: D:/upload/image/
  rootFilePath: D:/upload/
  mysql:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123
