
logging:
  level:
    root: warn # springboot框架本身的级别
  file:
    name: log/bolg.log
server:
  port: 8081
zzspace.blog:
  topk: 6
  avatar:
    tourist: /images/tourist.png
    admin: /images/admin.jpg
  imagePath: /upload/image/
  rootFilePath: /upload/
  mysql:
    url: jdbc:mysql://localhost:8081/blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: C3srajh98e
