logging:
  level:
    root: info # springboot框架本身的级别
    com.zzspace.blog: debug
  file:
    name: log/bolg.log
server:
  port: 8081
zzspace.blog:
  topk: 6
  avatar:
      tourist: /images/tourist.png
      admin: /images/admin.jpg
  imagePath: D://upload/image/
  filePath: D://upload/files/
  rootFilePath: D://upload/
